### ISSUE TITLE
ProxyCommand adb-connect failing (on Mac)

### ISSUE THREAD

**Issue by CNG** [google/adb-sync#11]
I followed the recommended setup for `adb-connect` using `ProxyCommand`, but it is not working. I am not sure which debug information is most relevant as I am unfamiliar with most of the commands run in the script. I suspect I might need the correct login name or put a key in the correct place, since the `adb-connect` script seems to work on its own, maybe.

It seemed `adb-connect` was failing in the last line, `socat stdio unix:"${t}/sock"`, based on `echo`s I placed on each line ("Running:" in output below) working except the final "Done".

```
ssh -v sshhelper
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/cgorichanaz/.ssh/config
debug1: /Users/cgorichanaz/.ssh/config line 1: Applying options for *
debug1: /Users/cgorichanaz/.ssh/config line 8: Applying options for sshhelper
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec adb-channel tcp:2222 com.arachnoid.sshelper/.SSHelperActivity 1
debug1: permanently_drop_suid: 501
debug1: identity file /Users/cgorichanaz/.ssh/cng1408 type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/cgorichanaz/.ssh/cng1408-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.numi4L
debug1: ssh_exchange_identification: Running: adb shell am start -W com.arachnoid.sshelper/.SSHelperActivity
debug1: ssh_exchange_identification: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.arachnoid.sshelper/.SSHelperActivity }
debug1: ssh_exchange_identification: Status: ok
debug1: ssh_exchange_identification: Activity: com.arachnoid.sshelper/.SSHelperActivity
debug1: ssh_exchange_identification: ThisTime: 1031
debug1: ssh_exchange_identification: TotalTime: 1031
debug1: ssh_exchange_identification: WaitTime: 1060
debug1: ssh_exchange_identification: Complete
debug1: ssh_exchange_identification: Running: adb forward localfilesystem:"/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.numi4L/sock" "tcp:2222"
debug1: ssh_exchange_identification: Running: socat stdio unix:"/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.numi4L/sock"
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to sshhelper:2222 as 'cgorichanaz'
debug1: SSH2_MSG_KEXINIT sent
Bad packet length 1349676916.
ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: message authentication code incorrect
```

When I manually entered the commands from `adb-connect`, it seemed to open a connection based on SSHelper log showing `sshd: Connection from 127.0.0.1 port 45008 on 127.0.0.1 port 2222`.

```
➜  ~ t=`mktemp -d -t adb-channel.XXXXXX | tee /dev/tty`
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.VvAB3N
➜  ~ adb shell am start -W com.arachnoid.sshelper/.SSHelperActivity
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.arachnoid.sshelper/.SSHelperActivity }
Status: ok
Activity: com.arachnoid.sshelper/.SSHelperActivity
ThisTime: 1083
TotalTime: 1083
WaitTime: 1123
Complete
➜  ~ adb forward localfilesystem:"${t}/sock" "tcp:2222"
➜  ~ socat -d -d -d -d stdio unix:"${t}/sock"
2017/04/09 23:18:30 socat[42517] D getpid()
2017/04/09 23:18:30 socat[42517] D getpid() -> 42517
2017/04/09 23:18:30 socat[42517] D setenv("SOCAT_PID", "42517", 1)
2017/04/09 23:18:30 socat[42517] D setenv() -> 0
2017/04/09 23:18:30 socat[42517] D setenv("SOCAT_PPID", "42517", 1)
2017/04/09 23:18:30 socat[42517] D setenv() -> 0
2017/04/09 23:18:30 socat[42517] I socat by Gerhard Rieger and contributors - see www.dest-unreach.org
2017/04/09 23:18:30 socat[42517] I This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit. (http://www.openssl.org/)
2017/04/09 23:18:30 socat[42517] I This product includes software written by Tim Hudson (tjh@cryptsoft.com)
2017/04/09 23:18:30 socat[42517] D socat version 1.7.3.2 on Jan 28 2017 18:25:05
2017/04/09 23:18:30 socat[42517] D setenv("SOCAT_VERSION", "1.7.3.2", 1)
2017/04/09 23:18:30 socat[42517] D setenv() -> 0
2017/04/09 23:18:30 socat[42517] D running on Darwin version Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64, release 16.5.0, machine x86_64
2017/04/09 23:18:30 socat[42517] D argv[0]: "socat"
2017/04/09 23:18:30 socat[42517] D argv[1]: "-d"
2017/04/09 23:18:30 socat[42517] D argv[2]: "-d"
2017/04/09 23:18:30 socat[42517] D argv[3]: "-d"
2017/04/09 23:18:30 socat[42517] D argv[4]: "-d"
2017/04/09 23:18:30 socat[42517] D argv[5]: "stdio"
2017/04/09 23:18:30 socat[42517] D argv[6]: "unix:/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.VvAB3N/sock"
2017/04/09 23:18:30 socat[42517] D sigaction(1, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D sigaction(2, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D sigaction(3, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D sigaction(4, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D sigaction(6, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D sigaction(10, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D sigaction(8, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D sigaction(11, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D sigaction(15, 0x7fff56113ea8, 0x0)
2017/04/09 23:18:30 socat[42517] D sigaction() -> 0
2017/04/09 23:18:30 socat[42517] D signal(13, 0x1)
2017/04/09 23:18:30 socat[42517] D signal() -> 0x0
2017/04/09 23:18:30 socat[42517] D atexit(0x109aee3da)
2017/04/09 23:18:30 socat[42517] D atexit() -> 0
2017/04/09 23:18:30 socat[42517] D calloc(1, 808)
2017/04/09 23:18:30 socat[42517] D calloc() -> 0x7fad63500400
2017/04/09 23:18:30 socat[42517] D malloc(1024)
2017/04/09 23:18:30 socat[42517] D malloc() -> 0x7fad64001000
2017/04/09 23:18:30 socat[42517] D calloc(1, 808)
2017/04/09 23:18:30 socat[42517] D calloc() -> 0x7fad635009a0
2017/04/09 23:18:30 socat[42517] D calloc(1, 808)
2017/04/09 23:18:30 socat[42517] D calloc() -> 0x7fad63500cd0
2017/04/09 23:18:30 socat[42517] D isatty(0)
2017/04/09 23:18:30 socat[42517] D isatty() -> 1
2017/04/09 23:18:30 socat[42517] D tcgetattr(0, 0x7fad63500af8)
2017/04/09 23:18:30 socat[42517] D tcgetattr(, {00006b02,00000003,00004b00,200005cf,04,ff,ff,7f,17,15,12,00,03,1c,1a,19,11,13,16,0f,01,00,14,00}) -> 0
2017/04/09 23:18:30 socat[42517] D isatty(1)
2017/04/09 23:18:30 socat[42517] D isatty() -> 1
2017/04/09 23:18:30 socat[42517] D tcgetattr(1, 0x7fad63500e28)
2017/04/09 23:18:30 socat[42517] D tcgetattr(, {00006b02,00000003,00004b00,200005cf,04,ff,ff,7f,17,15,12,00,03,1c,1a,19,11,13,16,0f,01,00,14,00}) -> 0
2017/04/09 23:18:30 socat[42517] D malloc(128)
2017/04/09 23:18:30 socat[42517] D malloc() -> 0x7fad63500730
2017/04/09 23:18:30 socat[42517] D malloc(128)
2017/04/09 23:18:30 socat[42517] D malloc() -> 0x7fad635007b0
2017/04/09 23:18:30 socat[42517] N reading from and writing to stdio
2017/04/09 23:18:30 socat[42517] D calloc(1, 808)
2017/04/09 23:18:30 socat[42517] D calloc() -> 0x7fad63501000
2017/04/09 23:18:30 socat[42517] D malloc(1024)
2017/04/09 23:18:30 socat[42517] D malloc() -> 0x7fad64001400
2017/04/09 23:18:30 socat[42517] D malloc(128)
2017/04/09 23:18:30 socat[42517] D malloc() -> 0x7fad63500890
2017/04/09 23:18:30 socat[42517] D malloc(128)
2017/04/09 23:18:30 socat[42517] D malloc() -> 0x7fad63500910
2017/04/09 23:18:30 socat[42517] N opening connection to LEN=74 AF=1 "/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.VvAB3N/sock"
2017/04/09 23:18:30 socat[42517] D socket(1, 1, 0)
2017/04/09 23:18:30 socat[42517] I socket(1, 1, 0) -> 5
2017/04/09 23:18:30 socat[42517] D fcntl(5, 2, 1)
2017/04/09 23:18:30 socat[42517] D fcntl() -> 0
2017/04/09 23:18:30 socat[42517] D connect(5, {1,LEN=74 AF=1 "/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.VvAB3N/sock"}, 74)
2017/04/09 23:18:30 socat[42517] D connect() -> 0
2017/04/09 23:18:30 socat[42517] D getsockname(5, 0x7fff561138f0, 0x7fff5611387c{108})
2017/04/09 23:18:30 socat[42517] D getsockname(, {LEN=16 AF=1 ""}, {16}) -> 0
2017/04/09 23:18:30 socat[42517] N successfully connected from local address LEN=16 AF=1 ""
2017/04/09 23:18:30 socat[42517] I resolved and opened all sock addresses
2017/04/09 23:18:30 socat[42517] D malloc(16385)
2017/04/09 23:18:30 socat[42517] D malloc() -> 0x7fad64001800
2017/04/09 23:18:30 socat[42517] N starting data transfer loop with FDs [0,1] and [5,5]
2017/04/09 23:18:30 socat[42517] D data loop: sock1->eof=0, sock2->eof=0, closing=0, wasaction=1, total_to={0.000000}
2017/04/09 23:18:30 socat[42517] D select(6, &0x21, &0x22, &0x0, NULL/0.000000)
2017/04/09 23:18:30 socat[42517] D select -> (, 0x0, 0x22, 0x0, NULL/0.000000), 2
2017/04/09 23:18:30 socat[42517] D data loop: sock1->eof=0, sock2->eof=0, closing=0, wasaction=1, total_to={0.000000}
2017/04/09 23:18:30 socat[42517] D select(6, &0x21, &0x0, &0x0, NULL/0.000000)
2017/04/09 23:18:30 socat[42517] D select -> (, 0x20, 0x0, 0x0, NULL/0.000000), 1
2017/04/09 23:18:30 socat[42517] D read(5, 0x7fad64001800, 8192)
2017/04/09 23:18:30 socat[42517] D read -> 21
2017/04/09 23:18:30 socat[42517] D write(1, 0x7fad64001800, 21)
SSH-2.0-OpenSSH_7.1
2017/04/09 23:18:30 socat[42517] D write -> 21
2017/04/09 23:18:30 socat[42517] I transferred 21 bytes from 5 to 1
2017/04/09 23:18:30 socat[42517] D data loop: sock1->eof=0, sock2->eof=0, closing=0, wasaction=1, total_to={0.000000}
2017/04/09 23:18:30 socat[42517] D select(6, &0x21, &0x2, &0x0, NULL/0.000000)
2017/04/09 23:18:30 socat[42517] D select -> (, 0x0, 0x2, 0x0, NULL/0.000000), 1
2017/04/09 23:18:30 socat[42517] D data loop: sock1->eof=0, sock2->eof=0, closing=0, wasaction=1, total_to={0.000000}
2017/04/09 23:18:30 socat[42517] D select(6, &0x21, &0x0, &0x0, NULL/0.000000)
^C2017/04/09 23:21:23 socat[42517] N socat_signal(): handling signal 2
2017/04/09 23:21:23 socat[42517] N exiting on signal 2
2017/04/09 23:21:23 socat[42517] N socat_signal(): finishing signal 2
2017/04/09 23:21:23 socat[42517] N exit(130)
2017/04/09 23:21:23 socat[42517] D starting xioexit()
2017/04/09 23:21:23 socat[42517] D tcsetattr(0, 0, {00006b02,00000003,00004b00,200005cf,04,ff,ff,7f,17,15,12,00,03,1c,1a,19,11,13,16,0f,01,00,14,00})
2017/04/09 23:21:23 socat[42517] D tcsetattr() -> 0
2017/04/09 23:21:23 socat[42517] D tcsetattr(1, 0, {00006b02,00000003,00004b00,200005cf,04,ff,ff,7f,17,15,12,00,03,1c,1a,19,11,13,16,0f,01,00,14,00})
2017/04/09 23:21:23 socat[42517] D tcsetattr() -> 0
2017/04/09 23:21:23 socat[42517] I shutdown(5, 2)
2017/04/09 23:21:23 socat[42517] D shutdown()  -> 0
2017/04/09 23:21:23 socat[42517] D finished xioexit()
➜  ~ adb forward --remove-all
➜  ~ rm -rf "${t}"
```

Same error with `ssh-copy-id`:

```
➜  ~ ssh-copy-id sshhelper
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.S1ejde
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.urVgpr

/usr/bin/ssh-copy-id: ERROR: Bad packet length 1349676916.
ERROR: ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: message authentication code incorrect
```

**Comment by divVerent** [comment]
That's odd.

Does adding a "sleep 1" in various places of the script help?

**Comment by CNG** [comment]
@divVerent I couldn't get any different result. But can you enlighten me about my question regarding the login name and key? Following the basic directions on the readme, my computer would be trying to do an ssh login using my macOS username. I tried various things like the SSHelper app's name `com.arachnoid.sshelper` or the result of `whoami` upon login with `adb shell`, which was just the name `shell`. Wouldn't I also need to get the SSH key into the appropriate place for that user? I thought some hangup there was causing it to silently fail.

**Comment by divVerent** [comment]
As for the sleep not helping - interesting, because you said running the
same commands manually does work.

I have a suspicion what this might be, but I am not entirely sure. Can you
use ssh with more -v flags? Can you log in when you use adb forward
manually to a TCP port?

As for which username: this is a SSHelper question, and I don't quite
remember the answer to it. IIRC it lets you use any username - but just in
case, I remember some SSH apps somewhere using "user@", "root@" too, so try
these as well. It's certainly not "shell". Installing the SSH key with
ssh-copy-id should work fine.

**Comment by CNG** [comment]
Since running the commands in `adb-channel` manually seems to work, I assumed the problem was with SSH and `ProxyCommand`. I am not sure how to log in (and ultimately run rsync) using just `adb-channel` but not in the context of `ProxyCommand`. I don't think I can somehow specify the local socket like I can a port?

For example, if I modify `adb-channel` to skip the socket creation and only do the following:

```
adb shell am start -W com.arachnoid.sshelper/.SSHelperActivity
adb forward tcp:2224 tcp:2222
sleep 100
```

I am then able to in a separate tab log in via `ssh -p2224 localhost` and I get this prompt (Apparently you're right the username doesn't matter.):

    u0_a58@angler:/data/data/com.arachnoid.sshelper/home $

I don't fully understand the merits of the socket versus port, or how to properly use this with `ProxyCommand` even if using two ports is fine. The script simply exits after the sleep since I commented out the `socat` that normally kept running. Add an infinite loop and rely on the trap exit?

Here is the output of the verbose SSH command using the unmodified `adb-connect` and suggested ssh config:

```
➜  ~ ssh -v -v -v sshhelper
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/cgorichanaz/.ssh/config
debug1: /Users/cgorichanaz/.ssh/config line 1: Applying options for *
debug1: /Users/cgorichanaz/.ssh/config line 8: Applying options for sshhelper
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec adb-channel tcp:2222 com.arachnoid.sshelper/.SSHelperActivity 3
debug1: permanently_drop_suid: 501
debug1: identity file /Users/cgorichanaz/.ssh/cng1408 type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/cgorichanaz/.ssh/cng1408-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.zpfvgW
debug1: ssh_exchange_identification: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.arachnoid.sshelper/.SSHelperActivity }

debug1: ssh_exchange_identification: Status: ok

debug1: ssh_exchange_identification: Activity: com.arachnoid.sshelper/.SSHelperActivity

debug1: ssh_exchange_identification: ThisTime: 1575

debug1: ssh_exchange_identification: TotalTime: 9977

debug1: ssh_exchange_identification: WaitTime: 1582

debug1: ssh_exchange_identification: Complete

debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH* compat 0x04000000
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug1: Authenticating to sshhelper:2222 as 'cgorichanaz'
debug3: put_host_port: [sshhelper]:2222
debug3: hostkeys_foreach: reading file "/Users/cgorichanaz/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
Bad packet length 1349676916.
debug3: send packet: type 1
ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: message authentication code incorrect
```

When I just run the `adb-channel` command, the last output is `SSH-2.0-OpenSSH_7.1` and it does not return to a prompt:

```
➜  ~ adb-channel tcp:2222 com.arachnoid.sshelper/.SSHelperActivity 1
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.a49eV8
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.arachnoid.sshelper/.SSHelperActivity }
Status: ok
Activity: com.arachnoid.sshelper/.SSHelperActivity
ThisTime: 1611
TotalTime: 26374
WaitTime: 1621
Complete
SSH-2.0-OpenSSH_7.1
```

**Comment by divVerent** [comment]
Thanks.

So I can see that either adb or socat must have corrupted data during the
forwarding.

The merit of using a unix socket rather than a TCP port is that it's easier
to create a temporary one, and it's also more secure (as other users on the
same computer cannot access it).

Let's try one more thing:

- Use a tcp based adb forward.
- But instead of ssh -p2224 localhost, run:

ssh -oProxyCommand='socat stdio tcp:connect:localhost:2224/' sshelper

If this now fails too, we know it's socat corrupting the data - if this
works, adb is the likely suspect.



On Apr 11, 2017 18:38, "Charlie Gorichanaz" <notifications@github.com>
wrote:

Since running the commands in adb-channel manually seems to work, I assumed
the problem was with SSH and ProxyCommand. I am not sure how to log in (and
ultimately run rsync) using just adb-channel but not in the context of
ProxyCommand. I don't think I can somehow specify the local socket like I
can a port?

For example, if I modify adb-channel to skip the socket creation and only
do the following:

adb shell am start -W com.arachnoid.sshelper/.
SSHelperActivity
adb forward tcp:2224 tcp:2222
sleep 100

I am then able to in a separate tab log in via ssh -p2224 localhost and I
get this prompt (Apparently you're right the username doesn't matter.):

u0_a58@angler:/data/data/com.arachnoid.sshelper/home $

I don't fully understand the merits of the socket versus port, or how to
properly use this with ProxyCommand even if using two ports is fine. The
script simply exits after the sleep since I commented out the socat that
normally kept running. Add an infinite loop and rely on the trap exit?

Here is the output of the verbose SSH command using the unmodified
adb-connect and suggested ssh config:

➜  ~ ssh -v -v -v sshhelper
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/cgorichanaz/.ssh/config
debug1: /Users/cgorichanaz/.ssh/config line 1: Applying options for *
debug1: /Users/cgorichanaz/.ssh/config line 8: Applying options for sshhelper
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec adb-channel tcp:2222
com.arachnoid.sshelper/.SSHelperActivity 3
debug1: permanently_drop_suid: 501
debug1: identity file /Users/cgorichanaz/.ssh/cng1408 type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/cgorichanaz/.ssh/cng1408-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.zpfvgW
debug1: ssh_exchange_identification: Starting: Intent {
act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER]
cmp=com.arachnoid.sshelper/.SSHelperActivity }

debug1: ssh_exchange_identification: Status: ok

debug1: ssh_exchange_identification: Activity:
com.arachnoid.sshelper/.SSHelperActivity

debug1: ssh_exchange_identification: ThisTime: 1575

debug1: ssh_exchange_identification: TotalTime: 9977

debug1: ssh_exchange_identification: WaitTime: 1582

debug1: ssh_exchange_identification: Complete

debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH* compat 0x04000000
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug1: Authenticating to sshhelper:2222 as 'cgorichanaz'
debug3: put_host_port: [sshhelper]:2222
debug3: hostkeys_foreach: reading file "/Users/cgorichanaz/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
Bad packet length 1349676916.
debug3: send packet: type 1
ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: message
authentication code incorrect

When I just run the adb-channel command, the last output is
SSH-2.0-OpenSSH_7.1 and it does not return to a prompt:

➜  ~ adb-channel tcp:2222 com.arachnoid.sshelper/.SSHelperActivity 1
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.a49eV8
Starting: Intent { act=android.intent.action.MAIN
cat=[android.intent.category.LAUNCHER]
cmp=com.arachnoid.sshelper/.SSHelperActivity }
Status: ok
Activity: com.arachnoid.sshelper/.SSHelperActivity
ThisTime: 1611
TotalTime: 26374
WaitTime: 1621
Complete
SSH-2.0-OpenSSH_7.1

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/google/adb-sync/issues/11#issuecomment-293420803>, or mute
the thread

**Comment by CNG** [comment]
I appreciate your prompt help, so I'm posting this first before trying to understand better... I am a little unclear on what you're asking me to try. Running `ssh ... sshelper` would trigger my config that runs the existing ProxyCommand that uses my modified `adb-channel`... that didn't seem right. So maybe you just meant for me to first run `adb forward tcp:2224 tcp:2222` and then your suggested ssh command? But maybe you meant `localhost` at the end instead of `sshelper`?

```
➜  ~ adb forward tcp:2224 tcp:2222
➜  ~ ssh -oProxyCommand='socat stdio tcp:connect:localhost:2224/' localhost
2017/04/11 15:50:12 socat[18725] E tcp: wrong number of parameters (3 instead of 2)
ssh_exchange_identification: Connection closed by remote host
➜  ~ ssh -oProxyCommand='socat stdio tcp:connect:localhost:2224/' sshelper
2017/04/11 15:50:30 socat[18995] E tcp: wrong number of parameters (3 instead of 2)
ssh_exchange_identification: Connection closed by remote host
➜  ~ adb forward --list
8XV7N15A28005026 tcp:2224 tcp:2222

➜  ~ ssh -v -v -v -oProxyCommand='socat stdio tcp:connect:localhost:2224/' localhost
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/cgorichanaz/.ssh/config
debug1: /Users/cgorichanaz/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec socat stdio tcp:connect:localhost:2224/
debug1: permanently_drop_suid: 501
debug1: identity file /Users/cgorichanaz/.ssh/cng1408 type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/cgorichanaz/.ssh/cng1408-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
2017/04/11 15:52:36 socat[19290] E tcp: wrong number of parameters (3 instead of 2)
ssh_exchange_identification: Connection closed by remote host
```

**Comment by CNG** [comment]
The SSH command worked when I removed `:connect` and removed a previous fingerprint. One minute.

**Comment by CNG** [comment]
```
➜  ~ ssh -v -v -v -oProxyCommand='socat stdio tcp:localhost:2224/' localhost
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/cgorichanaz/.ssh/config
debug1: /Users/cgorichanaz/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec socat stdio tcp:localhost:2224/
debug1: permanently_drop_suid: 501
debug1: identity file /Users/cgorichanaz/.ssh/cng1408 type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/cgorichanaz/.ssh/cng1408-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH* compat 0x04000000
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug1: Authenticating to localhost:22 as 'cgorichanaz'
debug3: hostkeys_foreach: reading file "/Users/cgorichanaz/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,ecdsa-sha2-nistp256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:9Rrd0We/FWxFyUj7qZ9FXEbH+MCKQbCINey9ZUvfEaQ
debug3: hostkeys_foreach: reading file "/Users/cgorichanaz/.ssh/known_hosts"
The authenticity of host 'localhost (<no hostip for proxy command>)' can't be established.
ECDSA key fingerprint is SHA256:9Rrd0We/FWxFyUj7qZ9FXEbH+MCKQbCINey9ZUvfEaQ.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: /Users/cgorichanaz/.ssh/cng1408 (0x7fa92aa00d20), explicit
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 53
debug3: input_userauth_banner
SSHelper Version 8.5 Copyright 2014, P. Lutus
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,keyboard-interactive
debug3: start over, passed a different list publickey,keyboard-interactive
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/cgorichanaz/.ssh/cng1408
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg ssh-rsa blen 1047
debug2: input_userauth_pk_ok: fp SHA256:ZrFRZT0JH/v70HI4RdT63Rl6uPf5jX/UOiMBOkHQPXw
debug3: sign_and_send_pubkey: RSA SHA256:ZrFRZT0JH/v70HI4RdT63Rl6uPf5jX/UOiMBOkHQPXw
debug3: Search for item with query: {
    acct = "/Users/cgorichanaz/.ssh/cng1408";
    agrp = "com.apple.ssh.passphrases";
    class = genp;
    labl = "SSH: /Users/cgorichanaz/.ssh/cng1408";
    nleg = 1;
    "r_Data" = 1;
    svce = OpenSSH;
}
debug2: using passphrase from keychain
debug3: no authentication agent, not adding key
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to localhost (via proxy).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: proc
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 91
debug2: callback start
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
Environment:
  USER=u0_a58
  LOGNAME=u0_a58
  HOME=/data/data/com.arachnoid.sshelper/home
  PATH=/su/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/su/xbin:/system/xbin:/data/user/0/com.arachnoid.sshelper/bin
  MAIL=/var/mail/u0_a58
  SHELL=/system/bin/sh
  SSH_CLIENT=127.0.0.1 40367 2222
  SSH_CONNECTION=127.0.0.1 40367 127.0.0.1 2222
  SSH_TTY=/dev/pts/0
  TERM=xterm-256color
  ANDROID_ASSETS=/system/app
  ANDROID_BOOTLOGO=1
  ANDROID_DATA=/data
  ANDROID_ROOT=/system
  ANDROID_SOCKET_zygote=9
  ANDROID_STORAGE=/storage
  ASEC_MOUNTPOINT=/mnt/asec
  BOARD=angler
  BOOTCLASSPATH=/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycast
  DOWNLOAD_CACHE=/data/cache
  ENV=/data/user/0/com.arachnoid.sshelper/home/.profile
  EXTERNAL_STORAGE=/sdcard
  OSDATA=Nexus_6P:3.10.73-g4cd47b6
  SSHELPER=/data/user/0/com.arachnoid.sshelper
  SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar
  TZ=GMT8
Nexus_6P:3.10.73-g4cd47b6
u0_a58@angler:/data/data/com.arachnoid.sshelper/home $
```

**Comment by divVerent** [comment]
Thanks.

So I can see that either adb or socat must have corrupted data during the
forwarding.

The merit of using a unix socket rather than a TCP port is that it's easier
to create a temporary one, and it's also more secure (as other users on the
same computer cannot access it).

Let's try one more thing:

- Use a tcp based adb forward.
- But instead of ssh -p2224 localhost, run:

ssh -oProxyCommand='socat stdio tcp:localhost:2224'

Does that break it again? If so, it's socat - of not, it's adb.

On Apr 11, 2017 18:38, "Charlie Gorichanaz" <notifications@github.com>
wrote:

Since running the commands in adb-channel manually seems to work, I assumed
the problem was with SSH and ProxyCommand. I am not sure how to log in (and
ultimately run rsync) using just adb-channel but not in the context of
ProxyCommand. I don't think I can somehow specify the local socket like I
can a port?

For example, if I modify adb-channel to skip the socket creation and only
do the following:

adb shell am start -W com.arachnoid.sshelper/.
SSHelperActivity
adb forward tcp:2224 tcp:2222
sleep 100

I am then able to in a separate tab log in via ssh -p2224 localhost and I
get this prompt (Apparently you're right the username doesn't matter.):

u0_a58@angler:/data/data/com.arachnoid.sshelper/home $

I don't fully understand the merits of the socket versus port, or how to
properly use this with ProxyCommand even if using two ports is fine. The
script simply exits after the sleep since I commented out the socat that
normally kept running. Add an infinite loop and rely on the trap exit?

Here is the output of the verbose SSH command using the unmodified
adb-connect and suggested ssh config:

➜  ~ ssh -v -v -v sshhelper
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/cgorichanaz/.ssh/config
debug1: /Users/cgorichanaz/.ssh/config line 1: Applying options for *
debug1: /Users/cgorichanaz/.ssh/config line 8: Applying options for sshhelper
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec adb-channel tcp:2222
com.arachnoid.sshelper/.SSHelperActivity 3
debug1: permanently_drop_suid: 501
debug1: identity file /Users/cgorichanaz/.ssh/cng1408 type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/cgorichanaz/.ssh/cng1408-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.zpfvgW
debug1: ssh_exchange_identification: Starting: Intent {
act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER]
cmp=com.arachnoid.sshelper/.SSHelperActivity }

debug1: ssh_exchange_identification: Status: ok

debug1: ssh_exchange_identification: Activity:
com.arachnoid.sshelper/.SSHelperActivity

debug1: ssh_exchange_identification: ThisTime: 1575

debug1: ssh_exchange_identification: TotalTime: 9977

debug1: ssh_exchange_identification: WaitTime: 1582

debug1: ssh_exchange_identification: Complete

debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH* compat 0x04000000
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug1: Authenticating to sshhelper:2222 as 'cgorichanaz'
debug3: put_host_port: [sshhelper]:2222
debug3: hostkeys_foreach: reading file "/Users/cgorichanaz/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
Bad packet length 1349676916.
debug3: send packet: type 1
ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: message
authentication code incorrect

When I just run the adb-channel command, the last output is
SSH-2.0-OpenSSH_7.1 and it does not return to a prompt:

➜  ~ adb-channel tcp:2222 com.arachnoid.sshelper/.SSHelperActivity 1
/var/folders/jk/3fltf9vx0n15p2qhkpjx2zk80000gn/T/adb-channel.a49eV8
Starting: Intent { act=android.intent.action.MAIN
cat=[android.intent.category.LAUNCHER]
cmp=com.arachnoid.sshelper/.SSHelperActivity }
Status: ok
Activity: com.arachnoid.sshelper/.SSHelperActivity
ThisTime: 1611
TotalTime: 26374
WaitTime: 1621
Complete
SSH-2.0-OpenSSH_7.1

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/google/adb-sync/issues/11#issuecomment-293420803>, or mute
the thread

**Comment by divVerent** [comment]
Okay, so this is odd, as there's clearly an issue with adb then.

I think I'll add a workaround to adb-channel to use a TCP socket on OSX, or
something along these lines.

**Comment by CNG** [comment]
All right, thank you!

**Comment by CNG** [comment]
I'm not sure if it helps, but I was trying to understand better what the difference was between the failed connection over the socket and the successful one over TCP port. My understanding of `socat`, etc., is still very limited, but I was at least able to determine Android is sending a "Protocol mismatch" message right before that "Bad packet length" error.

```
2017/04/12 13:19:32 socat[93280] I transferred 19 bytes from 5 to 1
2017/04/12 13:19:32 socat[93280] D data loop: sock1->eof=0, sock2->eof=0, closing=0, wasaction=1, total_to={0.000000}
2017/04/12 13:19:32 socat[93280] D select(6, &0x21, &0x2, &0x0, NULL/0.000000)
2017/04/12 13:19:32 socat[93280] D select -> (, 0x0, 0x2, 0x0, NULL/0.000000), 1
2017/04/12 13:19:32 socat[93280] D data loop: sock1->eof=0, sock2->eof=0, closing=0, wasaction=1, total_to={0.000000}
Bad packet length 1349676916.
```

* [Socket listen to failed SSH connection (Protocol mismatch) over ADB forwarded socket to Android](https://gist.github.com/CNG/436264df4bff6d99208d67ce1f42a2c5)
* [TCPDump of SSH connection over ADB forwarded port to Android](https://gist.github.com/CNG/afd970322a1a5d8c85fddecc3ff3e232)

I was trying to see if there was some setting for `socat` that would help and looked at what calls `adb` was using to set up the socket, but it's all still over my head!

**Comment by divVerent** [comment]
I pushed a change to a new branch "adb-channel-tcp" that adds an environment variable to force operation over TCP.

So try this:

```
$ git pull
$ git checkout adb-channel-tcp
$ EXPERIMENTAL_ADB_CHANNEL_TCP_PORT=2224 ssh sshelper
```

Does this fix the problem, compared to:

```
$ ssh sshelper
```

If so, that'd be an odd case of data corruption - your dump does not show any obvious signs of it though.  It'd probably help to know what Android is seeing on its side - this will be hard to find out with SSHelper, though.

**Comment by CNG** [comment]
Sorry for delay, just FYI I won't be able to test till Friday. (Frustrations with hackintosh drove me to reformat.) Thank you!

**Comment by CNG** [comment]
Still no luck.

Starting from scratch on a new macOS 10.12.4 system, I authorized the computer on the Android screen and then tried connecting with and without the change. The `ssh -v -v -v` output was nearly the same for both ("debug1: permanently_drop_suid: 501" in a different order and the port method showing "WARNING: this ADB channel is open to everyone on this computer."). The SSH log on the Android was quite different.

**Full details**

`~/.ssh/config`:

```
Host *
    UseKeychain yes
    ServerAliveInterval 300
    ServerAliveCountMax 2
    IdentityFile ~/.ssh/cng1408

Host sshelper
  Port 2222
  ProxyCommand adb-channel tcp:%p com.arachnoid.sshelper/.SSHelperActivity 1
```

Installing `adb-sync` and attempting normal socket based connection:

```
$ cd /tmp
$ git clone https://github.com/google/adb-sync
Cloning into 'adb-sync'...
remote: Counting objects: 74, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 74 (delta 0), reused 0 (delta 0), pack-reused 70
Unpacking objects: 100% (74/74), done.
$ cd adb-sync
$ sudo cp adb-sync adb-channel /usr/local/bin/
$ ssh -v -v -v sshelper
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/cgorichanaz/.ssh/config
debug1: /Users/cgorichanaz/.ssh/config line 1: Applying options for *
debug1: /Users/cgorichanaz/.ssh/config line 7: Applying options for sshelper
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec adb-channel tcp:2222 com.arachnoid.sshelper/.SSHelperActivity 1
debug1: permanently_drop_suid: 501
debug1: identity file /Users/cgorichanaz/.ssh/cng1408 type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/cgorichanaz/.ssh/cng1408-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: ssh_exchange_identification: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.arachnoid.sshelper/.SSHelperActivity }

debug1: ssh_exchange_identification: Warning: Activity not started, its current task has been brought to the front

debug1: ssh_exchange_identification: Status: ok

debug1: ssh_exchange_identification: Activity: com.arachnoid.sshelper/.SSHelperActivity

debug1: ssh_exchange_identification: ThisTime: 0

debug1: ssh_exchange_identification: TotalTime: 0

debug1: ssh_exchange_identification: WaitTime: 12

debug1: ssh_exchange_identification: Complete

debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH* compat 0x04000000
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug1: Authenticating to sshelper:2222 as 'cgorichanaz'
debug3: put_host_port: [sshelper]:2222
debug3: hostkeys_foreach: reading file "/Users/cgorichanaz/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
Bad packet length 1349676916.
debug3: send packet: type 1
ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: message authentication code incorrect
```

That resulted in the following log in Android SSHelper:

```
2017-04-22 00:30:46 execCom:executing: "/system/bin/id"
2017-04-22 00:30:46 execCom::stdout result: uid=10058(u0_a58) gid=10058(u0_a58) groups=10058(u0_a58),3002(net_bt),3003(inet),9997(everybody),50058(all_a58) context=u:r:untrusted_app:s0:c512,c768
2017-04-22 00:30:46 execCom::exit value: true
2017-04-22 00:30:46 generateNewKey:Check: dsa key is present.
2017-04-22 00:30:46 generateNewKey:Check: rsa key is present.
2017-04-22 00:30:46 generateNewKey:Check: ecdsa key is present.
2017-04-22 00:30:46 execCom:executing: "bin/pidof","sshelper_sshd","ssh"
2017-04-22 00:30:46 execCom::exit value: false
2017-04-22 00:30:46 LogServer: restarting server on port: 8080
2017-04-22 00:30:46 ClipboardServer: restarting server on port: 8081
2017-04-22 00:30:46 LogServer: restarting server on port: 8080
2017-04-22 00:30:46 ClipboardServer: restarting server on port: 8081
2017-04-22 00:30:46 generateNewKey:Check: dsa key is present.
2017-04-22 00:30:46 generateNewKey:Check: rsa key is present.
2017-04-22 00:30:46 generateNewKey:Check: ecdsa key is present.
2017-04-22 00:30:46 Starting/restarting SSH server on port 2222
2017-04-22 00:30:46 sshd::*** Warning: This is a special debug mode set by "select data
2017-04-22 00:30:46 sshd::***          logging mode", only one login allowed before restart.
2017-04-22 00:30:46 sshd::***          To end this special mode, make a logging selection
2017-04-22 00:30:46 sshd::***          outside the "SSH Server Debug 1-3" region.
2017-04-22 00:30:46 sshd: debug2: load_server_config: filename /data/user/0/com.arachnoid.sshelper/etc/sshd_config
2017-04-22 00:30:46 sshd: debug2: load_server_config: done config len = 698
2017-04-22 00:30:46 sshd: debug2: parse_server_config: config /data/user/0/com.arachnoid.sshelper/etc/sshd_config len 698
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:24 setting HostKey /data/data/com.arachnoid.sshelper/home/.ssh/id_rsa
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:25 setting HostKey /data/data/com.arachnoid.sshelper/home/.ssh/id_dsa
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:26 setting HostKey /data/data/com.arachnoid.sshelper/home/.ssh/id_ecdsa
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:32 setting PubkeyAcceptedKeyTypes +ssh-dss
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:112 setting PrintLastLog no
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:115 setting UsePrivilegeSeparation no
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:116 setting PermitUserEnvironment yes
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:117 setting Compression yes
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:118 setting ClientAliveInterval 300
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:119 setting ClientAliveCountMax 5
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:120 setting UseDNS no
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:131 setting Subsystem sftp internal-sftp
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:134 setting AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:135 setting AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
2017-04-22 00:30:46 sshd: debug3: /data/user/0/com.arachnoid.sshelper/etc/sshd_config:136 setting AcceptEnv LC_IDENTIFICATION LC_ALL
2017-04-22 00:30:46 sshd: debug1: sshd version OpenSSH_7.1, OpenSSL 1.0.2g  1 Mar 2016
2017-04-22 00:30:46 sshd: debug1: private host key #0: ssh-dss SHA256:JBC6t8tcBcgs6/CIHxGVS+tARoHbvKbO0vYqDst1azc
2017-04-22 00:30:46 sshd: debug1: private host key #1: ssh-rsa SHA256:gESumGl+BL+0P7y7IXBDTnOOk634N76bHnjv/yI+E6k
2017-04-22 00:30:46 sshd: debug1: private host key #2: ssh-dss SHA256:JBC6t8tcBcgs6/CIHxGVS+tARoHbvKbO0vYqDst1azc
2017-04-22 00:30:46 sshd: debug1: private host key #3: ecdsa-sha2-nistp256 SHA256:9Rrd0We/FWxFyUj7qZ9FXEbH+MCKQbCINey9ZUvfEaQ
2017-04-22 00:30:46 sshd: debug1: setgroups() failed: Operation not permitted
2017-04-22 00:30:46 sshd: debug1: rexec_argv[0]='/data/user/0/com.arachnoid.sshelper/bin/sshelper_sshd'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[1]='-D'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[2]='-p'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[3]='2222'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[4]='-h'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[5]='/data/user/0/com.arachnoid.sshelper/home/.ssh/id_dsa'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[6]='-o PidFile /data/user/0/com.arachnoid.sshelper/etc/sshd.pid'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[7]='-f'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[8]='/data/user/0/com.arachnoid.sshelper/etc/sshd_config'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[9]='-ddd'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[10]='-e'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[11]='-o PasswordAuthentication no'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[12]='-o PermitTunnel yes'
2017-04-22 00:30:46 sshd: debug1: rexec_argv[13]='-o StrictModes yes'
2017-04-22 00:30:46 LogServer: restarting server on port: 8080
2017-04-22 00:30:46 sshd: debug1: rexec_argv[14]='-o Banner /data/user/0/com.arachnoid.sshelper/etc/banner2.txt'
2017-04-22 00:30:46 sshd: debug2: fd 3 setting O_NONBLOCK
2017-04-22 00:30:46 sshd: debug1: Bind to port 2222 on 0.0.0.0.
2017-04-22 00:30:46 sshd: Server listening on 0.0.0.0 port 2222.
2017-04-22 00:30:46 sshd: debug2: fd 4 setting O_NONBLOCK
2017-04-22 00:30:46 sshd: debug3: sock_set_v6only: set socket 4 IPV6_V6ONLY
2017-04-22 00:30:46 sshd: debug1: Bind to port 2222 on ::.
2017-04-22 00:30:46 sshd: Server listening on :: port 2222.
2017-04-22 00:30:46 ClipboardServer: restarting server on port: 8081
2017-04-22 00:30:47 LogServer: restarting server on port: 8080
2017-04-22 00:30:47 ClipboardServer: restarting server on port: 8081
2017-04-22 00:30:54 JmDNS Zeroconf:register service: _workstation._tcp.local
2017-04-22 00:30:56 JmDNS Zeroconf:register service: _sftp-ssh._tcp.local.
2017-04-22 00:30:57 LogServer: restarting server on port: 8080
2017-04-22 00:30:57 ClipboardServer: restarting server on port: 8081
2017-04-22 00:30:58 LogServer: restarting server on port: 8080
2017-04-22 00:30:58 ClipboardServer: restarting server on port: 8081
2017-04-22 00:30:59 JmDNS Zeroconf:register service: _ssh._tcp.local.
2017-04-22 00:31:02 JmDNS Zeroconf:register service: _rsync._tcp.local.
2017-04-22 00:31:04 JmDNS Zeroconf:register service: _http._tcp.local.
```

Then I tried with the TCP patch:

```
$ git checkout adb-channel-tcp
Switched to branch 'adb-channel-tcp'
Your branch is up-to-date with 'origin/adb-channel-tcp'.
$ sudo cp adb-sync adb-channel /usr/local/bin/
$ EXPERIMENTAL_ADB_CHANNEL_TCP_PORT=2224 ssh -v -v -v sshelper

OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/cgorichanaz/.ssh/config
debug1: /Users/cgorichanaz/.ssh/config line 1: Applying options for *
debug1: /Users/cgorichanaz/.ssh/config line 7: Applying options for sshelper
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec adb-channel tcp:2222 com.arachnoid.sshelper/.SSHelperActivity 1
debug1: identity file /Users/cgorichanaz/.ssh/cng1408 type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/cgorichanaz/.ssh/cng1408-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: permanently_drop_suid: 501
WARNING: this ADB channel is open to everyone on this computer.
debug1: ssh_exchange_identification: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.arachnoid.sshelper/.SSHelperActivity }

debug1: ssh_exchange_identification: Warning: Activity not started, its current task has been brought to the front

debug1: ssh_exchange_identification: Status: ok

debug1: ssh_exchange_identification: Activity: com.arachnoid.sshelper/.SSHelperActivity

debug1: ssh_exchange_identification: ThisTime: 577

debug1: ssh_exchange_identification: TotalTime: 577

debug1: ssh_exchange_identification: WaitTime: 591

debug1: ssh_exchange_identification: Complete

debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH* compat 0x04000000
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug1: Authenticating to sshelper:2222 as 'cgorichanaz'
debug3: put_host_port: [sshelper]:2222
debug3: hostkeys_foreach: reading file "/Users/cgorichanaz/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
Bad packet length 1349676916.
debug3: send packet: type 1
ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: message authentication code incorrect
```

That resulted in the following log in Android SSHelper:

```
2017-04-22 00:32:30 LogServer: restarting server on port: 8080
2017-04-22 00:32:30 ClipboardServer: restarting server on port: 8081
2017-04-22 00:32:30 LogServer: restarting server on port: 8080
2017-04-22 00:32:30 ClipboardServer: restarting server on port: 8081
2017-04-22 00:32:31 sshd: debug3: fd 5 is not O_NONBLOCK
2017-04-22 00:32:31 sshd: debug1: Server will not fork when running in debugging mode.
2017-04-22 00:32:31 sshd: debug3: send_rexec_state: entering fd = 8 config len 698
2017-04-22 00:32:31 sshd: debug3: ssh_msg_send: type 0
2017-04-22 00:32:31 sshd: debug3: send_rexec_state: done
2017-04-22 00:32:31 sshd: debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
2017-04-22 00:32:31 sshd: debug3: recv_rexec_state: entering fd = 5
2017-04-22 00:32:31 sshd: debug3: ssh_msg_recv entering
2017-04-22 00:32:31 sshd: debug3: recv_rexec_state: done
2017-04-22 00:32:31 sshd: debug2: parse_server_config: config rexec len 698
2017-04-22 00:32:31 sshd: debug3: rexec:24 setting HostKey /data/data/com.arachnoid.sshelper/home/.ssh/id_rsa
2017-04-22 00:32:31 sshd: debug3: rexec:25 setting HostKey /data/data/com.arachnoid.sshelper/home/.ssh/id_dsa
2017-04-22 00:32:31 sshd: debug3: rexec:26 setting HostKey /data/data/com.arachnoid.sshelper/home/.ssh/id_ecdsa
2017-04-22 00:32:31 sshd: debug3: rexec:32 setting PubkeyAcceptedKeyTypes +ssh-dss
2017-04-22 00:32:31 sshd: debug3: rexec:112 setting PrintLastLog no
2017-04-22 00:32:31 sshd: debug3: rexec:115 setting UsePrivilegeSeparation no
2017-04-22 00:32:31 sshd: debug3: rexec:116 setting PermitUserEnvironment yes
2017-04-22 00:32:31 sshd: debug3: rexec:117 setting Compression yes
2017-04-22 00:32:31 sshd: debug3: rexec:118 setting ClientAliveInterval 300
2017-04-22 00:32:31 sshd: debug3: rexec:119 setting ClientAliveCountMax 5
2017-04-22 00:32:31 sshd: debug3: rexec:120 setting UseDNS no
2017-04-22 00:32:31 sshd: debug3: rexec:131 setting Subsystem sftp internal-sftp
2017-04-22 00:32:31 sshd: debug3: rexec:134 setting AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
2017-04-22 00:32:31 sshd: debug3: rexec:135 setting AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
2017-04-22 00:32:31 sshd: debug3: rexec:136 setting AcceptEnv LC_IDENTIFICATION LC_ALL
2017-04-22 00:32:31 sshd: debug1: sshd version OpenSSH_7.1, OpenSSL 1.0.2g  1 Mar 2016
2017-04-22 00:32:31 sshd: debug1: private host key #0: ssh-dss SHA256:JBC6t8tcBcgs6/CIHxGVS+tARoHbvKbO0vYqDst1azc
2017-04-22 00:32:31 sshd: debug1: private host key #1: ssh-rsa SHA256:gESumGl+BL+0P7y7IXBDTnOOk634N76bHnjv/yI+E6k
2017-04-22 00:32:31 sshd: debug1: private host key #2: ssh-dss SHA256:JBC6t8tcBcgs6/CIHxGVS+tARoHbvKbO0vYqDst1azc
2017-04-22 00:32:31 sshd: debug1: private host key #3: ecdsa-sha2-nistp256 SHA256:9Rrd0We/FWxFyUj7qZ9FXEbH+MCKQbCINey9ZUvfEaQ
2017-04-22 00:32:31 sshd: debug1: setgroups() failed: Operation not permitted
2017-04-22 00:32:31 sshd: debug1: inetd sockets after dupping: 3, 3
2017-04-22 00:32:31 sshd: Connection from 127.0.0.1 port 37139 on 127.0.0.1 port 2222
2017-04-22 00:32:31 sshd: Bad protocol version identification '' from 127.0.0.1 port 37139
```

**Comment by CNG** [comment]
I'll need to review the code and retrace this tomorrow, but in case you're faster than me, my results are above. I modified the above comment so as to keep only the relevant info but preserve the first just in case. Please see the web page in case it doesn't email the modification.

**Comment by CNG** [comment]
This actually works fine on the socket when I manually run the commands. The problem seems to lie in `ProxyCommand`?

This works:

```
t=`mktemp -d -t adb-channel.XXXXXX`
adb forward --remove-all; adb shell am start -W com.arachnoid.sshelper/.SSHelperActivity; sleep 3; adb forward localfilesystem:${t}/sock tcp:2222;
ssh -v -v -v -oProxyCommand="sh -c 'socat stdio unix:${t}/sock'" localhost
```

This fails:

```
t=`mktemp -d -t adb-channel.XXXXXX`
ssh -v -v -v -oProxyCommand="sh -c 'adb forward --remove-all; adb shell am start -W com.arachnoid.sshelper/.SSHelperActivity; sleep 3; adb forward localfilesystem:${t}/sock tcp:2222; socat stdio unix:${t}/sock'" localhost
```

**Comment by CNG** [comment]
OK, the problem was with `adb shell` interfering with stdin. I was able to resolve the issue by using the flag `-n`, in https://github.com/google/adb-sync/pull/13

I did not think it was necessary to branch by operating system, but it would be good to confirm this still works as expected in Linux (and I would be interested to know if it really worked there without this change!).

**Comment by t-oster** [comment]
Hi. I am on ArchLinux and #13 is exactly the parameter to fix this for me. So it is not an OSX issue. Maybe it has to do with specific versions of ADB. However with #13 merged it works like a charm.
